# Generated by Django 4.1.7 on 2023-04-01 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='problems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainBlocks.problem'),
        ),
    ]
