# Generated by Django 4.1.7 on 2023-04-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainBlocks', '0002_alter_profile_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='problems',
        ),
        migrations.AddField(
            model_name='profile',
            name='problems',
            field=models.ManyToManyField(blank=True, null=True, to='mainBlocks.problem'),
        ),
    ]
