# Generated by Django 4.1.7 on 2023-05-29 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBlocks', '0002_delete_code_remove_problem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='parameters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TestCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
                ('expected_output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterBlocks.problem')),
            ],
        ),
    ]
