# Generated by Django 4.1.7 on 2023-05-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBlocks', '0003_problem_parameters_testcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_directives',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
