# Generated by Django 4.1.7 on 2023-05-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterBlocks', '0004_problem_test_directives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='pname',
            new_name='tname',
        ),
    ]
