# Generated by Django 4.1.7 on 2023-03-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialsBlocks', '0002_remove_tutorial_id_tutorial_block_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='valid_code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
