# Generated by Django 4.1.7 on 2023-03-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialsBlocks', '0004_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
