# Generated by Django 4.1.7 on 2023-03-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialsBlocks', '0005_tutorial_sequence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
