# Generated by Django 4.1.7 on 2023-05-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialsBlocks', '0006_delete_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='block_id',
            field=models.CharField(max_length=50),
        ),
    ]
