# Generated by Django 4.1.1 on 2022-10-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_as_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=20)),
                ('content', models.TextField(max_length=20)),
            ],
        ),
    ]
