# Generated by Django 4.1.1 on 2022-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='main_as_database',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='main_as_database',
            name='content',
            field=models.TextField(),
        ),
    ]
