# Generated by Django 4.1.1 on 2022-10-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_two_alter_main_as_database_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.TextField()),
                ('cat_decription', models.TextField()),
            ],
        ),
    ]
